version: 2

jobs:
  unit_test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: unit tests
          command: |
            #eval $(ssh-agent -s)
            #echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            #mkdir -p ~/.ssh
            #chmod 700 ~/.ssh
            #echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            #chmod 644 ~/.ssh/known_hosts
            git submodule init && git submodule sync && git submodule update --init --recursive && git submodule status
            apt-get update -qy
            apt-get install -y python-dev python-pip jq
            cd modules/charts/primehub
            pip3 install -r ../../primehub/vendor/zero-to-jupyterhub-k8s/images/hub/requirements.txt --upgrade
            pip3 install pytest-cov
            make test-html
            cd ../../primehub-admission
            pip3 install -r src/requirements.txt
            PYTHONPATH=../charts/primehub/scripts/jupyterhub/config/ py.test --cov=. --cov-report html
            cd ../../ci
            ./test-cov.sh

  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "d0:90:27:9c:dc:28:b5:3e:d8:18:0c:9a:64:46:6f:d4"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}

      - run:
          name: publish
          command: |
            ./ci/publish.sh

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"

workflows:
  version: 2
  release_builds:
    jobs:
      - unit_test
      # - build:
      #     filters:
      #       tags:
      #         only: /v.*/
      #       branches:
              ignore: /.*/
